name: ServerHomes
version: '1.1'
main: com.zip.serverhomes.Main
api-version: 1.19
commands:
  delhome:
    description: Delete a home
    usage: /<command> [home]
  sethome:
    description: Set a home
    usage: /<command> [home]
  home:
    description: Teleport to a set home
    usage: /<command> [home]