name: ServerHomes
version: '1.4'
main: com.zip.serverhomes.Main
api-version: 1.19
commands:
  delhome:
    description: Delete a home
    usage: /<command> [home]
    permission: com.zip.homes.home
  sethome:
    description: Set a home
    usage: /<command> [home]
    permission: com.zip.homes.home
  home:
    description: Teleport to a set home
    usage: /<command> [home]
    permission: com.zip.homes.home
  homeas:
    description: Admin command used to allow staff to run home commands as another player
    usage: /<command> [player]
    permission: com.zip.homes.admin